defaults:
  - finetune

handler: SelfBalancingDPO

args:
  learning_rate: 1e-5
  num_train_epochs: 5

method_args:
  alpha: 1.0
  gamma: 1.0
  beta: 0.1
  score_scale: 2.0

  scorer:
    _target_: scorers.LearnedScorer
    cfg:
      _target_: scorers.ScorerConfig
      input_dimension: 2048
      layers: 1
      scale_factor: 1.0
      use_sigmoid: true
      zero_init: true
      use_bias: true
    pretrained_path: null

  scorer_pretrain:
    _target_: trainer.unlearn.sb.ScorerPretrainConfig
    epochs: 0
    lr: 5.0e-2
    freeze_after: false

  scorer_trainer:
    _target_: trainer.unlearn.Scorer.ScorerTrainerSBDPO
    _partial_: true
    lambda_entropy: 1.0
    lambda_population: 1.0
    budget: 0.2
    lambda_l2: 0.01
    beta: ${..beta}
    score_scale: ${..score_scale}
    optim_cfg:
      _target_: trainer.unlearn.Scorer.ScorerOptimConfig
      lr: 5.0e-2
      weight_decay: 1.0e-4
      momentum: 0.9
      update_every_n_steps: 10
      grad_clip: 1.0
      loss_reduction: mean
