defaults:
  - finetune

handler: SelfBalancingGradDiff

args: # HuggingFace TrainingArguments
  learning_rate: 1e-5
  num_train_epochs: 5

method_args:
  alpha: 1.0
  gamma: 1.0

  forget_loss:
    _target_: trainer.unlearn.sb.SequenceWiseNLL
    use_softmax: false

  retain_loss:
    _target_: trainer.unlearn.sb.SequenceWiseNLL
  scorer_trainer:
    # OLD scorer trainer (no regularization):
    # _target_: trainer.unlearn.Scorer.ScorerTrainerGradDiff
    # _partial_: true

    # Scorer with regularization
    # _target_: trainer.unlearn.Scorer.ScorerTrainerRegularized
    # _partial_: true
    # rho_ent: 1.0
    # rho_pop: 1.0
    # alpha_budget: 0.2

    _target_: trainer.unlearn.Scorer.ScorerTrainerRegularizedL2
    _partial_: true
    rho_ent: 1.0
    rho_pop: 1.0
    alpha_budget: 0.2
    rho_l2: 0.01

    cfg:
      _target_: trainer.unlearn.Scorer.ScorerConfig
      input_dimension: 4096
      # input_dimension: 2048
      layers: 1
      scale_factor: 1.0
      use_sigmoid: true
      zero_init: true
      use_bias: true

    optim_cfg:
      _target_: trainer.unlearn.Scorer.ScorerOptimConfig
      # lr: 1.0e-1
      lr: 5.0e-2
      weight_decay: 1.0e-4
      momentum: 0.9
      update_every_n_steps: 10
      grad_clip: 1.0
      loss_reduction: mean
      # warmup_ratio: 0.1
