# @package eval.paraphrase.metrics.mia_gradnorm
defaults:
  - ../../../data/datasets@datasets: TOFU_MIA
  - ../../../collator@collators: DataCollatorForSupervisedDatasetwithIndex

handler: mia_gradnorm
batch_size: 1
p: 2

datasets:
  TOFU_QA_forget:
    args:
      hf_args:
        name: ${eval.paraphrase.forget_split}_perturbed
      question_key: ${eval.paraphrase.question_key}
  TOFU_QA_holdout:
    args:
      hf_args:
        name: ${eval.paraphrase.holdout_split}
