# @package eval.rwku.metrics.mia_raw_loss
defaults:
  - ../../data/datasets@datasets: RWKU_MIA
  - ../../collator@collators: DataCollatorForSupervisedDatasetwithIndex

batch_size: 8
handler: mia_raw_loss

datasets:
  RWKU_MIA_forget:
    args:
      hf_args:
        filter_column: "subject"
        filter_values: ${eval.rwku.forget_subjects}
  RWKU_MIA_holdout:
    args:
      hf_args:
        filter_column: "subject"
        filter_values: ${eval.rwku.retain_subjects}
