# @package eval.paraphrase.metrics.mia_min_k_plus_plus
defaults:
  - ../../../data/datasets@datasets: RWKU_MIA
  - ../../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
batch_size: ${eval.paraphrase.batch_size}
handler: mia_min_k_plus_plus
k: 0.4
