# @package eval.paraphrase.metrics.mia_min_k
defaults:
  - ../../../data/datasets@datasets: MUSE_MIA
  - ../../../collator@collators: DataCollatorForSupervisedDatasetwithIndex
batch_size: ${eval.paraphrase.batch_size}
handler: mia_min_k
k: 0.4
